name: update-json-versions

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert:
    name: Create JSON files from blueprints
    runs-on: ubuntu-latest

    steps:
    - name: install pigz
      run: |
        sudo apt-get install pigz -y

    - name: checkout repo
      uses: actions/checkout@v4

    - name: convert files
      run: |
        git config user.name "github-actions[dranothecat-bot]"
        git config user.email "dranothecat-bot@users.noreply.github.com"
        OIFS=${IFS}
        export IFS=$'\n'
        files_found=0
        for dir in $(ls blueprints); do
          echo "Processing ${dir}..."
          if [ ! -d json/${dir} ]; then
            mkdir -p json/${dir}
          fi
          for file in $(ls "blueprints/${dir}"); do
            ff="blueprints/${dir}/${file}"
            echo "  Found ${ff}"
            files_found=$((files_found+1))
            cat ${ff} | cut -c2- | base64 -d | pigz -d | json_pp > "json/${dir}/${file}.json"
            git add "json/${dir}/${file}.json"
          done
        done
        if [ ${files_found} > 0 ]; then
          echo "Found ${files_found} blueprints."
          git status
          git commit -m "generated ${files_found} json files"
          git push
        fi
        IFS=${OIFS}
