name: update-json-versions

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert:
    name: Create JSON files and rendered images from updated or new blueprints
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pigz -y
        cd lib
        pip3 install -r requirements.txt
        playwright install --with-deps chromium

    - name: convert files
      run: |
        git config user.name "github-actions[dranothecat-bot]"
        git config user.email "dranothecat-bot@users.noreply.github.com"
        OIFS=${IFS}
        export IFS=$'\n'
        files_found=0
        files_modified=0
        for dir in $(ls blueprints); do
          echo "Processing ${dir}..."
          if [ ! -d generated_json/${dir} ]; then
            mkdir -p generated_json/${dir}
          fi
          for file in $(ls "blueprints/${dir}"); do
            ff="blueprints/${dir}/${file}"
            echo "  Found ${ff}"
            files_found=$((files_found+1))
            if [ -f "generated_json/${dir}/${file}.json" ]; then
              cp "generated_json/${dir}/${file}.json" /tmp
              cat ${ff} | cut -c2- | base64 -d | pigz -d | json_pp > "generated_json/${dir}/${file}.json"
              if ! diff "generated_json/${dir}/${file}.json" "/tmp/${file}.json" >/dev/null; then
                if python3 lib/render_image.py "$(cat ${ff})" "blueprints/${dir}/${file}.png" ; then
                  files_modified=$((files_modified+1))
                  git add "generated_json/${dir}/${file}.json" "blueprints/${dir}/${file}.png"
                fi
              fi
            else
              cat ${ff} | cut -c2- | base64 -d | pigz -d | json_pp > "generated_json/${dir}/${file}.json"
              if python3 lib/render_image.py "$(cat ${ff})" "blueprints/${dir}/${file}.png" ; then
                files_modified=$((files_modified+1))
                git add "generated_json/${dir}/${file}.json" "blueprints/${dir}/${file}.png"
              fi
            fi
          done
        done
        if [ ${files_modified} -gt 0 ]; then
          echo "Found ${files_found} and modified ${files_modified} blueprints."
          git status
          git commit -m "generated ${files_modified} json files and images"
          git push
        fi
        IFS=${OIFS}
