name: update-json-versions

on:
  push:
    branches:
      - main

jobs:
  convert:
    name: Convert base64 pigz encoded files to json
    runs-on: ubuntu-latest

    steps:
    - name: install pigz
      run: |
        sudo apt-get install pigz -y

    - name: checkout repo
      uses: actions/checkout@v4

    - name: convert files
      run: |
        for dir in $(ls blueprints); do
          echo ${dir}
        done
