name: update-json-versions

on:
  push:
    branches:
      - main

jobs:
  convert:
    name: Convert base64 pigz encoded files to json
    runs-on: ubuntu-latest

    steps:
    - name: install pigz
      run: |
        sudo apt-get install pigz -y

    - name: checkout repo
      uses: actions/checkout@v4

    - name: convert files
      run: |
        OIFS=${IFS}
        export IFS=$'\n'
        for dir in $(ls blueprints); do
          echo "Processing ${dir}..."
          for file in $(ls "blueprints/${dir}"); do
            ls -l "blueprints/${dir}/${file}"
          done
        done
        IFS=${OIFS}
