name: update-json-versions

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert:
    name: Create JSON files from blueprints
    runs-on: ubuntu-latest

    steps:
    - name: install pigz
      run: |
        sudo apt-get install pigz -y

    - name: checkout repo
      uses: actions/checkout@v4

    - name: convert files
      run: |
        git config user.name "github-actions[dranothecat-bot]"
        git config user.email "dranothecat-bot@users.noreply.github.com"
        OIFS=${IFS}
        export IFS=$'\n'
        files_found=0
        files_modified=0
        for dir in $(ls blueprints); do
          echo "Processing ${dir}..."
          if [ ! -d json/${dir} ]; then
            mkdir -p json/${dir}
          fi
          for file in $(ls "blueprints/${dir}"); do
            ff="blueprints/${dir}/${file}"
            echo "  Found ${ff}"
            files_found=$((files_found+1))
            if [ -f "json/${dir}/${file}.json" ]; then
              cp "json/${dir}/${file}.json" /tmp
              cat ${ff} | cut -c2- | base64 -d | pigz -d | json_pp > "json/${dir}/${file}.json"
              diff "json/${dir}/${file}.json" "/tmp/${file}.json"
              if [ ! $(diff "json/${dir}/${file}.json" "/tmp/${file}.json") ]; then
                files_modified=$((files_modified+1))
                git add "json/${dir}/${file}.json"
              fi
            else
              cat ${ff} | cut -c2- | base64 -d | pigz -d | json_pp > "json/${dir}/${file}.json"
              files_modified=$((files_modified+1))
              git add "json/${dir}/${file}.json"
            fi
          done
        done
        if [ ${files_modified} -gt 0 ]; then
          echo "Found ${files_found} and modified ${files_modified} blueprints."
          git status
          git commit -m "generated ${files_modified} json files"
          git push
        fi
        IFS=${OIFS}
